name: Publicar no CPanel

on: workflow_dispatch

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        local-dir: "./dist/"
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
